### ISSUE TITLE
jupyter-lab: command not found from start.sh

### ISSUE THREAD

**Issue by Guzzii** [cerebrotech/workspace-configs#22]
Hi guys. I am having issues with using my custom docker image on domino. I am getting the following error when the docker is running the start.sh file.
```bash 
/var/opt/workspaces/Jupyterlab/start.sh: line 22: jupyter-lab: command not found
```
If I understand correctly, it is running the shell script as a non-root user `ubuntu`. I have made the `PATH` variable to have `conda` location. The Dockerfile is as follows,
```
USER root

RUN conda install -y fastparquet python-snappy tensorflow-gpu=1.10
RUN apt-get update && apt-get install -y neovim htop gcc
RUN pip install -U xgboost jupyterlab hyperopt dask keras networkx==1.11

RUN  git clone --branch 2018q2-v1.1 https://github.com/dominodatalab/workspace-configs.git /var/opt/workspaces && \
    rm -rf /var/opt/workspaces/workspace-logos

RUN useradd ubuntu && usermod -aG root ubuntu
RUN mkdir -p /home/ubuntu/.jupyter && \
    printf "\nc.NotebookApp.token = u'' \n\n" >> /home/ubuntu/.jupyter/jupyter_notebook_config.py && \
    chown -R root:ubuntu /home/ubuntu/.jupyter && \
    chown -R root:ubuntu /home/ubuntu/

USER ubuntu
ENV PATH="/opt/conda/bin:${PATH}"
```
Could you advise how to solve the issue? Thanks in advance.

**Comment by johnjoo1** [comment]
It's unclear what base image you're starting from, but if it had worked before you changed the PATH variable, you may want to look at this support article on how to change PATH so that it's available for the user inside a Domino Run. 

https://support.dominodatalab.com/hc/en-us/articles/115004581903-PATH-environment-cannot-be-set-for-a-run

I also noticed that you used `pip install jupyterlab` to install Jupyterlab. There could be multiple pips in your image. If you're using conda, you'll want to make sure `which pip` points to the the pip inside conda.

**Comment by ChuckRIHead** [comment]
Closing this older issue. Please re-open if you encounter the same issue again.
